# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActivityOpenConfig.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x41\x63tivityOpenConfig.proto\x12\x08resource\"\x88\x03\n\x12\x41\x63tivityOpenConfig\x12\x12\n\nActivityID\x18\x01 \x01(\x05\x12\x14\n\x0c\x41\x63tivityName\x18\x02 \x01(\t\x12\x14\n\x0c\x41\x63tivityType\x18\x03 \x01(\x05\x12\x19\n\x11\x41\x63tivityTypeParam\x18\x04 \x01(\x05\x12\x16\n\x0e\x41\x63tivityUIType\x18\x05 \x01(\x05\x12\x11\n\tOpenLevel\x18\x06 \x01(\x05\x12\x16\n\x0e\x43reateRoleDays\x18\x07 \x01(\x05\x12\x0e\n\x06SortID\x18\x08 \x01(\x05\x12\x10\n\x08OpenType\x18\t \x01(\x05\x12\x11\n\tOpenParam\x18\n \x03(\x03\x12\x1a\n\x12StatisticsOpenTime\x18\x0b \x01(\r\x12\x18\n\x10OpenSvrTimeLimit\x18\x0c \x01(\r\x12\x11\n\tDelayTime\x18\r \x01(\r\x12\x19\n\x11IsNeedSelectSubID\x18\x0e \x01(\x05\x12 \n\x18\x41\x63tOpenLaterSvrOpenLimit\x18\x0f \x01(\x05\x12\x19\n\x11IsNeedSelectSvrID\x18\x10 \x01(\x05\"D\n\x16\x41\x63tivityOpenConfigList\x12*\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1c.resource.ActivityOpenConfigB\x15Z\x13./resource;resourceb\x06proto3')



_ACTIVITYOPENCONFIG = DESCRIPTOR.message_types_by_name['ActivityOpenConfig']
_ACTIVITYOPENCONFIGLIST = DESCRIPTOR.message_types_by_name['ActivityOpenConfigList']
ActivityOpenConfig = _reflection.GeneratedProtocolMessageType('ActivityOpenConfig', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVITYOPENCONFIG,
  '__module__' : 'ActivityOpenConfig_pb2'
  # @@protoc_insertion_point(class_scope:resource.ActivityOpenConfig)
  })
_sym_db.RegisterMessage(ActivityOpenConfig)

ActivityOpenConfigList = _reflection.GeneratedProtocolMessageType('ActivityOpenConfigList', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVITYOPENCONFIGLIST,
  '__module__' : 'ActivityOpenConfig_pb2'
  # @@protoc_insertion_point(class_scope:resource.ActivityOpenConfigList)
  })
_sym_db.RegisterMessage(ActivityOpenConfigList)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\023./resource;resource'
  _ACTIVITYOPENCONFIG._serialized_start=39
  _ACTIVITYOPENCONFIG._serialized_end=431
  _ACTIVITYOPENCONFIGLIST._serialized_start=433
  _ACTIVITYOPENCONFIGLIST._serialized_end=501
# @@protoc_insertion_point(module_scope)
